name: check_wsl
on:
  # Run this workflow only manually
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: Vampire/setup-wsl@v3
      with:
        distribution: Ubuntu-22.04
    - name: List installed WSL distributions
      run: wsl -l -v
